service: PhotoDrop

frameworkVersion: "3"

plugins:
  - serverless-esbuild
  - serverless-plugin-existing-s3

provider:
  name: aws
  runtime: nodejs16.x
  profile: myawff
  region: us-east-1
  httpApi:
    cors:
      allowedOrigins: ["*"]
      allowedHeaders: ["*"]
    authorizers:
      photographersAuthorizer:
        type: request
        functionName: AuthorizeUser
        identitySource: $request.header.Authorization
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
          Resource:
            - "arn:aws:s3:::photo-drop-images/*"
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
          Resource:
            - "arn:aws:s3:::photo-drop-images/*"
        - Effect: "Allow"
          Action:
            - sns:Publish
          Resource: "*"
  environment:
    PHOTO_DROP_DB_USERNAME: ${ssm:PHOTO_DROP_DB_USERNAME}
    PHOTO_DROP_DB_PASSWORD: ${ssm:PHOTO_DROP_DB_PASSWORD}
    PHOTO_DROP_DB_ENDPOINT: ${ssm:PHOTO_DROP_DB_ENDPOINT}
    PHOTO_DROP_DB_PORT: ${ssm:DEFAULT_DB_PORT}
    PHOTO_DROP_DB_NAME: PhotoDropDB
    ACCESS_TOKEN_SECRET: ${ssm:ACCESS_TOKEN_SECRET}
    REFRESH_TOKEN_SECRET: ${ssm:REFRESH_TOKEN_SECRET}
    BUCKET_NAME: photo-drop-images
    WATERMARK_KEY: ${ssm:WATERMARK_KEY}
    REGION: us-east-1
    AWS_ACCOUNT_ID: ${AWS::AccountId}

functions: ${file(yml/functions.yml)}
resources: ${file(yml/resources.yml)}
