export type EnvVariables =
  | "PHOTO_DROP_DB_USERNAME"
  | "PHOTO_DROP_DB_PASSWORD"
  | "PHOTO_DROP_DB_ENDPOINT"
  | "PHOTO_DROP_DB_PORT"
  | "PHOTO_DROP_DB_NAME"
  | "ACCESS_TOKEN_SECRET"
  | "REFRESH_TOKEN_SECRET"
  | "BUCKET_NAME"
  | "WATERMARK_KEY"
  | "REGION"
  | "AWS_ACCOUNT_ID";
